services:
  mongodb:
    image: mongo:latest
    container_name: mongodbTareas
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27018:27018"
    volumes:
      - ./mongodb_data:/data/db
